SQL> SELECT Customer_ID, Customer_Name, Category FROM Customer ORDER BY Category;

CUSTOMER_ID          CUSTOMER_NAME                                      CATEGORY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
-------------------- -------------------------------------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
C4                   Paxton Coffey                                      Loyal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
C5                   Elizabeth Frank                                    Loyal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
C3                   Elvis Cooper                                       Privileged                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
C6                   Raegan Bullock                                     Regular                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
C2                   Sonny Chase                                        Regular                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
C7                   Leia Osborne                                       VIP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
C1                   Kendall Krueger                                    VIP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

7 rows selected.

SQL> spool off
