SQL> SELECT Staff_ID, Staff_Name, Salary FROM Staff ORDER BY Salary DESC;

STAFF STAFF_NAME                                             SALARY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
----- -------------------------------------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
S7    Timothy Rocha                                           13000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
S2    Virginia Murray                                         12000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
S5    Maren Shea                                              11000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
S1    Cole Gamble                                             10000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
S3    Ignacio Patel                                            9000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
S4    Ellie Russell                                            9000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
S6    Barbara Rivers                                           8000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

7 rows selected.

SQL> spool off
