SQL> SELECT a.Painting_ID, a.Painting_Name, b.Order_Type, c.Paying_Price FROM Painting a JOIN Order_Painting b ON a.Painting_ID = b.Painting_ID JOIN Customer_Painting c ON a.Painting_ID = c.Painting_ID WHERE Order_Type = 'Lease' AND ROWNUM <= 5 ORDER BY Paying_Price DESC;

PAINTING_I PAINTING_NAME                                                                                                                                          ORDER PAYING_PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
---------- ------------------------------------------------------------------------------------------------------------------------------------------------------ ----- ------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
P7         Water Lilies                                                                                                                                           Lease         2475                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
P2         The Mona Lisa                                                                                                                                          Lease         1275                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
P7         Water Lilies                                                                                                                                           Lease          784                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
P2         The Mona Lisa                                                                                                                                          Lease          143                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
P3         Hare                                                                                                                                                   Lease           85                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

SQL> spool off
